# ----- config/config.ini ----- #
[project]
# base_url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
base_url = https://www.saucedemo.com
browser = chrome
headless = false
timeout = 10

[allure]
report_dir = allure-results
title = Test Execution Report

[database]
host = localhost
port = 3306
user = scott
password = tiger
database = mydb
driver = mysql+pymysql